package com.myowntrip.app.ui.theme

import androidx.compose.ui.graphics.Color

/**
 * M3 color roles from [docs/design-system/variables.json] (colección M3 · modos Light/Dark).
 * UI must consume [androidx.compose.material3.MaterialTheme.colorScheme], not these directly.
 */
object AppColors {
  val backgroundLight = Color(0xFFF7F4EF)
  val errorLight = Color(0xFF904A42)
  val errorContainerLight = Color(0xFFFFDAD5)
  val inverseOnSurfaceLight = Color(0xFFF9EFE2)
  val inversePrimaryLight = Color(0xFFB4BAC0)
  val inverseSurfaceLight = Color(0xFF353027)
  val onBackgroundLight = Color(0xFF191C20)
  val onErrorLight = Color(0xFFFFFFFF)
  val onErrorContainerLight = Color(0xFF73342C)
  val onPrimaryLight = Color(0xFFFFFFFF)
  val onPrimaryContainerLight = Color(0xFF2E363D)
  val onPrimaryFixedLight = Color(0xFF1C2228)
  val onPrimaryFixedVariantLight = Color(0xFF3A444C)
  val onSecondaryLight = Color(0xFFFFFFFF)
  val onSecondaryContainerLight = Color(0xFF2E363D)
  val onSecondaryFixedLight = Color(0xFF1C2228)
  val onSecondaryFixedVariantLight = Color(0xFF2E363D)
  val onSurfaceLight = Color(0xFF1F1B13)
  val onSurfaceVariantLight = Color(0xFF4C4639)
  val onTertiaryLight = Color(0xFFFFFFFF)
  val onTertiaryContainerLight = Color(0xFF663E00)
  val onTertiaryFixedLight = Color(0xFF2B1700)
  val onTertiaryFixedVariantLight = Color(0xFF663E00)
  val outlineLight = Color(0xFF7D7667)
  val outlineVariantLight = Color(0xFFCEC6B4)
  val primaryLight = Color(0xFF4A5864)
  val primaryContainerLight = Color(0xFFE4E1DC)
  val primaryFixedLight = Color(0xFFE4E1DC)
  val primaryFixedDimLight = Color(0xFF98A1AA)
  val scrimLight = Color(0xFF000000)
  val secondaryLight = Color(0xFF4A5864)
  val secondaryContainerLight = Color(0xFFE4E1DC)
  val secondaryFixedLight = Color(0xFFE4E1DC)
  val secondaryFixedDimLight = Color(0xFF98A1AA)
  val shadowLight = Color(0xFF000000)
  val surfaceLight = Color(0xFFFFF8F2)
  val surfaceBrightLight = Color(0xFFFFF8F2)
  val surfaceContainerLight = Color(0xFFF6EDDF)
  val surfaceContainerHighLight = Color(0xFFF1E7D9)
  val surfaceContainerHighestLight = Color(0xFFEBE1D4)
  val surfaceContainerLowLight = Color(0xFFFCF2E5)
  val surfaceContainerLowestLight = Color(0xFFFFFFFF)
  val surfaceDimLight = Color(0xFFE2D9CC)
  val surfaceTintLight = Color(0xFF4A5864)
  val surfaceVariantLight = Color(0xFFEBE1CF)
  val tertiaryLight = Color(0xFF825513)
  val tertiaryContainerLight = Color(0xFFFFDDB8)
  val tertiaryFixedLight = Color(0xFFFFDDB8)
  val tertiaryFixedDimLight = Color(0xFFF8BB71)

  val backgroundDark = Color(0xFF111318)
  val errorDark = Color(0xFFFFB4AA)
  val errorContainerDark = Color(0xFF73342C)
  val inverseOnSurfaceDark = Color(0xFF353027)
  val inversePrimaryDark = Color(0xFF4A5864)
  val inverseSurfaceDark = Color(0xFFEBE1D4)
  val onBackgroundDark = Color(0xFFE1E2E9)
  val onErrorDark = Color(0xFF561E18)
  val onErrorContainerDark = Color(0xFFFFDAD5)
  val onPrimaryDark = Color(0xFF1A2228)
  val onPrimaryContainerDark = Color(0xFFE4E1DC)
  val onPrimaryFixedDark = Color(0xFF1C2228)
  val onPrimaryFixedVariantDark = Color(0xFF3A444C)
  val onSecondaryDark = Color(0xFF1A2228)
  val onSecondaryContainerDark = Color(0xFFE4E1DC)
  val onSecondaryFixedDark = Color(0xFF1C2228)
  val onSecondaryFixedVariantDark = Color(0xFF3A444C)
  val onSurfaceDark = Color(0xFFEBE1D4)
  val onSurfaceVariantDark = Color(0xFFCEC6B4)
  val onTertiaryDark = Color(0xFF472A00)
  val onTertiaryContainerDark = Color(0xFFFFDDB8)
  val onTertiaryFixedDark = Color(0xFF2B1700)
  val onTertiaryFixedVariantDark = Color(0xFF663E00)
  val outlineDark = Color(0xFF989080)
  val outlineVariantDark = Color(0xFF4C4639)
  val primaryDark = Color(0xFFB4BAC2)
  val primaryContainerDark = Color(0xFF3A444C)
  val primaryFixedDark = Color(0xFFE4E1DC)
  val primaryFixedDimDark = Color(0xFF98A1AA)
  val scrimDark = Color(0xFF000000)
  val secondaryDark = Color(0xFFB4BAC2)
  val secondaryContainerDark = Color(0xFF3A444C)
  val secondaryFixedDark = Color(0xFFE4E1DC)
  val secondaryFixedDimDark = Color(0xFF98A1AA)
  val shadowDark = Color(0xFF000000)
  val surfaceDark = Color(0xFF17130B)
  val surfaceBrightDark = Color(0xFF3E392F)
  val surfaceContainerDark = Color(0xFF231F17)
  val surfaceContainerHighDark = Color(0xFF2E2921)
  val surfaceContainerHighestDark = Color(0xFF39342B)
  val surfaceContainerLowDark = Color(0xFF1F1B13)
  val surfaceContainerLowestDark = Color(0xFF110E07)
  val surfaceDimDark = Color(0xFF17130B)
  val surfaceTintDark = Color(0xFFB4BAC2)
  val surfaceVariantDark = Color(0xFF4C4639)
  val tertiaryDark = Color(0xFFF8BB71)
  val tertiaryContainerDark = Color(0xFF663E00)
  val tertiaryFixedDark = Color(0xFFFFDDB8)
  val tertiaryFixedDimDark = Color(0xFFF8BB71)

  val successLight = Color(0xFF0D631B)
  val successDark = Color(0xFF88D982)
  val warningLight = Color(0xFF815611)
  val warningDark = Color(0xFFF6BC70)
  val infoLight = Color(0xFF5A6572)
  val infoDark = Color(0xFFB4BAC2)
}
